In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mb

In [8]:
db=pd.read_csv("C:\\Users\\Admin\\Desktop\\dataset\\iris.csv")
db.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Dependent and independent variables

In [16]:
X=db.iloc[:,0:5]
y=db.iloc[:,-1:]


# Train test Split

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 122)
print("X-train:",X_train.shape)
print("Y-train:",y_train.shape)
print("Y-test:",X_test.shape)
print("Y-test:",y_test.shape)

X-train: (105, 5)
Y-train: (105, 1)
Y-test: (45, 5)
Y-test: (45, 1)


# Model import

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
knn=KNeighborsClassifier(n_neighbors=35,metric='euclidean')

# Model Fitting

In [50]:
knn.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=35, p=2,
                     weights='uniform')

# Model Prediction 

In [51]:
y_pred=knn.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor'], dtype=object)

# Confusion Matrix

In [52]:
from sklearn.metrics import confusion_matrix
c_m=confusion_matrix(y_test,y_pred)
print(c_m)

[[13  0  0]
 [ 0 16  0]
 [ 0  0 16]]


# Accuracy

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
#act_pred=pd.Dataframe({"actual:",y_test,"Pred1:",y_pred})

1.0