Ans 1:
         
         An array is a data structure that contains a group of elements. Typically these elements are all of 
         the same data type, such as an integer or string. Arrays are commonly used in computer programs to 
         organize data so that a related set of values can be easily sorted or searched.

Ans 2:
    
        The differences between lists and arrays in Python:

        1.Arrays need to be declared. Lists don’t, since they are built into Python.
        
        2.Arrays can store data very compactly and are more efficient for storing large amounts of data.
        
        3.Arrays are great for numerical operations; lists cannot directly handle math operations. 
       
        

Ans 3:


        The reshape() function is used to give a new shape to an array without changing its data

Ans 4:

            Python string method strip() returns a copy of the string in which all chars have been stripped 
            from the beginning and the end of the string (default whitespace characters).

            Syntax
            Following is the syntax for strip() method −

                    str.strip([chars]);
            
            Parameters
            chars − The characters to be removed from beginning or end of the string
            
            Return Value
            This method returns a copy of the string in which all chars have been stripped from the 
            beginning and the end of the string.
            
            Example:-
            
            #!/usr/bin/python

            str = "0000000this is string example....wow!!!0000000";
            print str.strip( '0' )
            
            output:-
            
            this is string example....wow!!!

Ans 5

    To create strings that span multiple lines, triple single quotes ''' or triple double quotes """ are used 
    to enclose the string.



Ans 6

In [4]:
array1=['a','b','c','d']

array1

['a', 'b', 'c', 'd']

Ans 7

In [5]:
arr="hello"
arr[2:4]


'll'

Ans 8 :

In [9]:
a=[12,56,78,32,90,23,44,102,65,9]
b=max(a)
print("Maximun Integer:-",b)
c=min(a)
print("Minimum Integer:-",c)



Maximun Integer:- 102
Minimum Integer:- 9


Ans 9:

In [26]:
nm="core python"
a=nm[5:]
print(a)
b=a
strlen=len(b)
c=str[strlen::-1]
print("Reverse String :-",c)

python
Reverse String :- nohtyP


Ans 10 :



In [31]:
a=[56,78,32,90,23,44,102,65,9]
a.append(12)
print("new array:-",a)
a.remove(102)
print("Updated array:-",a)

new array:- [56, 78, 32, 90, 23, 44, 102, 65, 9, 12]
Updated array:- [56, 78, 32, 90, 23, 44, 65, 9, 12]


Ans 11 :
    

In [41]:

import numpy as np
print("One dimensional array:-")
arr1=np.array([1,2,3,4])
print(arr1)
print("Three dimensional array:-",)
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[12, 22, 23], [45, 55, 56]]])

print(arr)


One dimensional array:-
[1 2 3 4]
Three dimensional array:-
[[[ 1  2  3]
  [ 4  5  6]]

 [[12 22 23]
  [45 55 56]]]


Ans 12:

In [49]:
a= "Programiz"
print("Upper case:-",a.upper())
print("Lower case:-",a.lower())
a=a.replace("Programiz","Program")
print("Replace:-",a)

Upper case:- PROGRAMIZ
Lower case:- programiz
Replace:- Program


 Ans 13 :
    

In [65]:
import numpy as np
arr1=np.linspace(1,10,5,dtype=int)
print(arr1)
arr2=np.arange(1,10,2,dtype=int)
print(arr2)
arr3=arr1-arr2
print("subtraction:-",arr3)

[ 1  3  5  7 10]
[1 3 5 7 9]
subtraction:- [0 0 0 0 1]


Ans 14:

In [69]:
str="happy new year"
a=str.split()
a

['happy', 'new', 'year']

In [81]:
a="hi this is me"
b='this'
print(" check if string "+b + " is in string "+a)
print(b in a)
print(" check if string "+a+" is in string "+b)
print(a in b)

 check if string this is in string hi this is me
True
 check if string hi this is me is in string this
False
